//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encuesta()
        {
            this.EncuestaPregunta = new HashSet<EncuestaPregunta>();
            this.RespuestaEncuesta = new HashSet<RespuestaEncuesta>();
        }
    
        public int EncuestaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaTentativaAplicacion { get; set; }
        public decimal CostoEstimado { get; set; }
        public bool EsAlcanceNacional { get; set; }
        public int NroEncuestasAplicadas { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioRegistroId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaPregunta> EncuestaPregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaEncuesta> RespuestaEncuesta { get; set; }
    }
}
