//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaPregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaPregunta()
        {
            this.EncuestaOpcion = new HashSet<EncuestaOpcion>();
        }
    
        public int EncuestaPreguntaId { get; set; }
        public int EncuestaId { get; set; }
        public string Texto { get; set; }
        public string Tipo { get; set; }
        public int Orden { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioRegistroId { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaOpcion> EncuestaOpcion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
