//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaOpcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaOpcion()
        {
            this.RespuestaEncuestaOpcion = new HashSet<RespuestaEncuestaOpcion>();
        }
    
        public int EncuestaOpcionId { get; set; }
        public int EncuestaPreguntaId { get; set; }
        public string Texto { get; set; }
        public int Orden { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioRegistroId { get; set; }
    
        public virtual EncuestaPregunta EncuestaPregunta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaEncuestaOpcion> RespuestaEncuestaOpcion { get; set; }
    }
}
