//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<EncuestaOpcion> EncuestaOpcion { get; set; }
        public virtual DbSet<EncuestaPregunta> EncuestaPregunta { get; set; }
        public virtual DbSet<PersonaNatural> PersonaNatural { get; set; }
        public virtual DbSet<RespuestaEncuesta> RespuestaEncuesta { get; set; }
        public virtual DbSet<RespuestaEncuestaOpcion> RespuestaEncuestaOpcion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
