//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaEncuestaOpcion
    {
        public int RespuestaEncuestaOpcionId { get; set; }
        public int RespuestaEncuestaId { get; set; }
        public int EncuestaOpcionId { get; set; }
        public string Valor { get; set; }
    
        public virtual EncuestaOpcion EncuestaOpcion { get; set; }
        public virtual RespuestaEncuesta RespuestaEncuesta { get; set; }
    }
}
