//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasNUnit
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaEncuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RespuestaEncuesta()
        {
            this.RespuestaEncuestaOpcion = new HashSet<RespuestaEncuestaOpcion>();
        }
    
        public int RespuestaEncuestaId { get; set; }
        public int PersonaNaturalId { get; set; }
        public int EncuestaId { get; set; }
        public System.DateTime FechaEncuesta { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        public virtual PersonaNatural PersonaNatural { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaEncuestaOpcion> RespuestaEncuestaOpcion { get; set; }
    }
}
